# Generated by Django 3.2 on 2021-05-04 21:08

import companies.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20210503_0352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='company',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True, validators=[companies.validations.validate_cnpj]),
        ),
    ]
