# Generated by Django 3.2 on 2021-05-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210503_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(),
        ),
    ]
